export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST"
export const FETCH_COMPLETED_REQUEST = "FETCH_COMPLETED_REQUEST"
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE"
export const FETCH_COMPLETED_FAILURE = "FETCH_COMPLETED_FAILURE"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"
export const FETCH_COMPLETED_SUCCESS = "FETCH_COMPLETED_SUCCESS"

export const TASK_COMPLETED_REQUEST = "TASK_COMPLETED_REQUEST"
export const TASK_COMPLETED_FAILURE = "TASK_COMPLETED_FAILURE"
// export const TASK_COMPLETED_SUCCESS = "TASK_COMPLETED_SUCCESS"

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST"
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE"
// export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
